name: Deploy to IONOS Webspace

on:
  push:
    branches:
      - main  # Change this to match your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build  # Adjust based on your project setup

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: "ftps"
          port: 21
          local-dir: ./dist/
          server-dir: /build/
